package com.humzaman.removed.util;

public enum ResultCode {
    SUBMISSION,
    VALID_COMMENT,
    INVALID_COMMENT,
    NOT_REDDIT_LINK,
    NOT_URL,
    MORE_DETAILS,
    ABOUT,
    FAILED,
    NO_INTERNET,
    NO_DATA_FOUND,
    PUSHSHIFT_404,
    PUSHSHIFT_500,
    PUSHSHIFT_502,
    PUSHSHIFT_503,
    PUSHSHIFT_504,
    PUSHSHIFT_OTHER,
    UNKNOWN_ERROR,
    TIMEOUT
}
