package com.humzaman.removed.util;

public enum ResultCode {
    SUBMISSION,
    VALID_COMMENT,
    INVALID_COMMENT,
    NOT_REDDIT_LINK,
    NOT_URL,
    MORE_DETAILS,
    ABOUT,
    FAILED,
    NO_INTERNET,
    NO_DATA_FOUND,
    PULLPUSH_404,
    PULLPUSH_500,
    PULLPUSH_502,
    PULLPUSH_503,
    PULLPUSH_504,
    PULLPUSH_OTHER,
    UNKNOWN_ERROR,
    TIMEOUT
}
